### ISSUE TITLE
Message constructors

### ISSUE THREAD

**Issue by MeanSquaredError** [rbeeli/websocketclient-cpp#11]
Hi,
While looking at the `Message` class, I noticed that it has three constructors
```
Message(MessageType type, span<byte> data)
Message(MessageType type, string& data)
Message(MessageType type, string_view data)
```
The last constructor works fine with `const` strings, because the string view is essentially `const`. However the first two constructors don't work with const data. Also I see that the third constructor internally uses a `const_cast` to make the `string_view` data non-const.

I think it makes sense to change the constructors to
```
Message(MessageType type, span<byte> data)
Message(MessageType type, span<const byte> data)
Message(MessageType type, const string& data)
Message(MessageType type, string_view data)
```
This way it will accept any `const` strings and spans without a problem.
Then it also makes sense to change
```
    span<byte> data;
```
to
```
    span<const byte> data;
```
This will remove the need for `const_cast`s in the constructors.
What do you think?

**Comment by MeanSquaredError** [comment]
Maybe it is possible to get rid of this constructor
```
Message(MessageType type, string& data)
```
because the `string_view` constructor takes care of the case when the argument is `const strings&`.

**Comment by rbeeli** [comment]
Hi,

See https://github.com/rbeeli/websocketclient-cpp/commit/78068b3aa3a4e59ce96006465bfe00894e576cce. I have added a `span<const byte>` constructor and dropped `string&` since `string_view` covers that case as you said. `Message`, for now, is writeable, maybe at some point I'll consider making it read-only, i.e. `span<const byte>`. One reason is to be able to do in-place parsing.

**Comment by MeanSquaredError** [comment]
Great, this will let me remove one or two explicit string constructors in my code. Thank you!
